<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="1" tests="3" time="0.320" timestamp="2024-05-23T16:43:02.399325" hostname="kalman"><testcase classname="plansys2_data_collector.test.test_copyright" name="test_copyright" time="0.000"><skipped type="pytest.skip" message="No copyright header has been placed in the generated source file.">/home/kalman/plansys2_ws/src/plansys2_data_collector/test/test_copyright.py:20: No copyright header has been placed in the generated source file.</skipped></testcase><testcase classname="plansys2_data_collector.test.test_flake8" name="test_flake8" time="0.221"><failure message="AssertionError: Found 46 code style errors / warnings:&#10;  ./setup.py:3:1: I201 Missing newline between import groups. 'from setuptools import find_packages, setup' is identified as Third Party and 'import os' is identified as Stdlib.&#10;  ./plansys2_data_collector/csv_generator.py:2:2: W291 trailing whitespace&#10;  ./plansys2_data_collector/csv_generator.py:6:2: W291 trailing whitespace&#10;  ./plansys2_data_collector/csv_generator.py:8:2: W291 trailing whitespace&#10;  ./plansys2_data_collector/csv_generator.py:17:1: F401 'rosbags.rosbag2.Reader' imported but unused&#10;  ./plansys2_data_collector/csv_generator.py:18:1: I100 Import statements are in the wrong order. 'from rosbags.highlevel import AnyReader' should be before 'from rosbags.rosbag2 import Reader'&#10;  ./plansys2_data_collector/csv_generator.py:21:1: I100 Import statements are in the wrong order. 'from pathlib import Path' should be before 'from rosbags.highlevel import AnyReader' and in a different group.&#10;  ./plansys2_data_collector/csv_generator.py:39:100: E501 line too long (100 &gt; 99 characters)&#10;  ./plansys2_data_collector/csv_generator.py:46:1: W293 blank line contains whitespace&#10;  ./plansys2_data_collector/csv_generator.py:48:100: E501 line too long (107 &gt; 99 characters)&#10;  ./plansys2_data_collector/csv_generator.py:74:1: E302 expected 2 blank lines, found 1&#10;  ./plansys2_data_collector/csv_generator.py:76:5: F841 local variable 'node' is assigned to but never used&#10;  ./plansys2_data_collector/csv_generator.py:82:1: E305 expected 2 blank lines after class or function definition, found 1&#10;  ./plansys2_data_collector/plot_generator.py:2:2: W291 trailing whitespace&#10;  ./plansys2_data_collector/plot_generator.py:6:2: W291 trailing whitespace&#10;  ./plansys2_data_collector/plot_generator.py:8:2: W291 trailing whitespace&#10;  ./plansys2_data_collector/plot_generator.py:17:1: I100 Import statements are in the wrong order. 'import pandas' should be before 'from rclpy.node import Node'&#10;  ./plansys2_data_collector/plot_generator.py:19:1: I100 Import statements are in the wrong order. 'import matplotlib.pyplot' should be before 'import seaborn'&#10;  ./plansys2_data_collector/plot_generator.py:20:1: I100 Import statements are in the wrong order. 'import sys' should be before 'import matplotlib.pyplot' and in a different group.&#10;  ./plansys2_data_collector/plot_generator.py:20:1: I201 Missing newline between import groups. 'import sys' is identified as Stdlib and 'import matplotlib.pyplot' is identified as Third Party.&#10;  ./plansys2_data_collector/plot_generator.py:21:1: I201 Missing newline between import groups. 'import numpy' is identified as Third Party and 'import sys' is identified as Stdlib.&#10;  ./plansys2_data_collector/plot_generator.py:23:1: E302 expected 2 blank lines, found 1&#10;  ./plansys2_data_collector/plot_generator.py:33:100: E501 line too long (102 &gt; 99 characters)&#10;  ./plansys2_data_collector/plot_generator.py:43:29: Q000 Double quotes found but single quotes preferred&#10;  ./plansys2_data_collector/plot_generator.py:56:100: Q000 Double quotes found but single quotes preferred&#10;  ./plansys2_data_collector/plot_generator.py:56:100: E501 line too long (103 &gt; 99 characters)&#10;  ./plansys2_data_collector/plot_generator.py:57:100: E501 line too long (105 &gt; 99 characters)&#10;  ./plansys2_data_collector/plot_generator.py:57:102: Q000 Double quotes found but single quotes preferred&#10;  ./plansys2_data_collector/plot_generator.py:58:100: E501 line too long (107 &gt; 99 characters)&#10;  ./plansys2_data_collector/plot_generator.py:58:104: Q000 Double quotes found but single quotes preferred&#10;  ./plansys2_data_collector/plot_generator.py:59:100: E501 line too long (105 &gt; 99 characters)&#10;  ./plansys2_data_collector/plot_generator.py:59:102: Q000 Double quotes found but single quotes preferred&#10;  ./plansys2_data_collector/plot_generator.py:64:100: E501 line too long (104 &gt; 99 characters)&#10;  ./plansys2_data_collector/plot_generator.py:67:100: E501 line too long (105 &gt; 99 characters)&#10;  ./plansys2_data_collector/plot_generator.py:70:100: E501 line too long (108 &gt; 99 characters)&#10;  ./plansys2_data_collector/plot_generator.py:73:100: E501 line too long (102 &gt; 99 characters)&#10;  ./plansys2_data_collector/plot_generator.py:79:28: Q000 Double quotes found but single quotes preferred&#10;  ./plansys2_data_collector/plot_generator.py:85:1: E302 expected 2 blank lines, found 1&#10;  ./plansys2_data_collector/plot_generator.py:87:5: F841 local variable 'node' is assigned to but never used&#10;  ./plansys2_data_collector/plot_generator.py:93:1: E305 expected 2 blank lines after class or function definition, found 1&#10;  ./launch/plot.launch.py:49:1: W293 blank line contains whitespace&#10;  ./launch/plot.launch.py:58:14: W292 no newline at end of file&#10;  ./launch/generate_csv.launch.py:28:100: E501 line too long (101 &gt; 99 characters)&#10;  ./launch/generate_csv.launch.py:34:1: W293 blank line contains whitespace&#10;  ./launch/generate_csv.launch.py:44:1: W293 blank line contains whitespace&#10;  ./launch/generate_csv.launch.py:52:14: W292 no newline at end of file&#10;assert 1 == 0">test/test_flake8.py:23: in test_flake8
    assert rc == 0, \
E   AssertionError: Found 46 code style errors / warnings:
E     ./setup.py:3:1: I201 Missing newline between import groups. 'from setuptools import find_packages, setup' is identified as Third Party and 'import os' is identified as Stdlib.
E     ./plansys2_data_collector/csv_generator.py:2:2: W291 trailing whitespace
E     ./plansys2_data_collector/csv_generator.py:6:2: W291 trailing whitespace
E     ./plansys2_data_collector/csv_generator.py:8:2: W291 trailing whitespace
E     ./plansys2_data_collector/csv_generator.py:17:1: F401 'rosbags.rosbag2.Reader' imported but unused
E     ./plansys2_data_collector/csv_generator.py:18:1: I100 Import statements are in the wrong order. 'from rosbags.highlevel import AnyReader' should be before 'from rosbags.rosbag2 import Reader'
E     ./plansys2_data_collector/csv_generator.py:21:1: I100 Import statements are in the wrong order. 'from pathlib import Path' should be before 'from rosbags.highlevel import AnyReader' and in a different group.
E     ./plansys2_data_collector/csv_generator.py:39:100: E501 line too long (100 &gt; 99 characters)
E     ./plansys2_data_collector/csv_generator.py:46:1: W293 blank line contains whitespace
E     ./plansys2_data_collector/csv_generator.py:48:100: E501 line too long (107 &gt; 99 characters)
E     ./plansys2_data_collector/csv_generator.py:74:1: E302 expected 2 blank lines, found 1
E     ./plansys2_data_collector/csv_generator.py:76:5: F841 local variable 'node' is assigned to but never used
E     ./plansys2_data_collector/csv_generator.py:82:1: E305 expected 2 blank lines after class or function definition, found 1
E     ./plansys2_data_collector/plot_generator.py:2:2: W291 trailing whitespace
E     ./plansys2_data_collector/plot_generator.py:6:2: W291 trailing whitespace
E     ./plansys2_data_collector/plot_generator.py:8:2: W291 trailing whitespace
E     ./plansys2_data_collector/plot_generator.py:17:1: I100 Import statements are in the wrong order. 'import pandas' should be before 'from rclpy.node import Node'
E     ./plansys2_data_collector/plot_generator.py:19:1: I100 Import statements are in the wrong order. 'import matplotlib.pyplot' should be before 'import seaborn'
E     ./plansys2_data_collector/plot_generator.py:20:1: I100 Import statements are in the wrong order. 'import sys' should be before 'import matplotlib.pyplot' and in a different group.
E     ./plansys2_data_collector/plot_generator.py:20:1: I201 Missing newline between import groups. 'import sys' is identified as Stdlib and 'import matplotlib.pyplot' is identified as Third Party.
E     ./plansys2_data_collector/plot_generator.py:21:1: I201 Missing newline between import groups. 'import numpy' is identified as Third Party and 'import sys' is identified as Stdlib.
E     ./plansys2_data_collector/plot_generator.py:23:1: E302 expected 2 blank lines, found 1
E     ./plansys2_data_collector/plot_generator.py:33:100: E501 line too long (102 &gt; 99 characters)
E     ./plansys2_data_collector/plot_generator.py:43:29: Q000 Double quotes found but single quotes preferred
E     ./plansys2_data_collector/plot_generator.py:56:100: Q000 Double quotes found but single quotes preferred
E     ./plansys2_data_collector/plot_generator.py:56:100: E501 line too long (103 &gt; 99 characters)
E     ./plansys2_data_collector/plot_generator.py:57:100: E501 line too long (105 &gt; 99 characters)
E     ./plansys2_data_collector/plot_generator.py:57:102: Q000 Double quotes found but single quotes preferred
E     ./plansys2_data_collector/plot_generator.py:58:100: E501 line too long (107 &gt; 99 characters)
E     ./plansys2_data_collector/plot_generator.py:58:104: Q000 Double quotes found but single quotes preferred
E     ./plansys2_data_collector/plot_generator.py:59:100: E501 line too long (105 &gt; 99 characters)
E     ./plansys2_data_collector/plot_generator.py:59:102: Q000 Double quotes found but single quotes preferred
E     ./plansys2_data_collector/plot_generator.py:64:100: E501 line too long (104 &gt; 99 characters)
E     ./plansys2_data_collector/plot_generator.py:67:100: E501 line too long (105 &gt; 99 characters)
E     ./plansys2_data_collector/plot_generator.py:70:100: E501 line too long (108 &gt; 99 characters)
E     ./plansys2_data_collector/plot_generator.py:73:100: E501 line too long (102 &gt; 99 characters)
E     ./plansys2_data_collector/plot_generator.py:79:28: Q000 Double quotes found but single quotes preferred
E     ./plansys2_data_collector/plot_generator.py:85:1: E302 expected 2 blank lines, found 1
E     ./plansys2_data_collector/plot_generator.py:87:5: F841 local variable 'node' is assigned to but never used
E     ./plansys2_data_collector/plot_generator.py:93:1: E305 expected 2 blank lines after class or function definition, found 1
E     ./launch/plot.launch.py:49:1: W293 blank line contains whitespace
E     ./launch/plot.launch.py:58:14: W292 no newline at end of file
E     ./launch/generate_csv.launch.py:28:100: E501 line too long (101 &gt; 99 characters)
E     ./launch/generate_csv.launch.py:34:1: W293 blank line contains whitespace
E     ./launch/generate_csv.launch.py:44:1: W293 blank line contains whitespace
E     ./launch/generate_csv.launch.py:52:14: W292 no newline at end of file
E   assert 1 == 0</failure></testcase><testcase classname="plansys2_data_collector.test.test_pep257" name="test_pep257" time="0.023" /></testsuite></testsuites>